// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0FD6rG451mXMLk5mgNYa8e-rRTS2o7o',
    appId: '1:550001479730:web:40a8943bea7f38af872c2b',
    messagingSenderId: '550001479730',
    projectId: 'prakflutterfirebase-f5460',
    authDomain: 'prakflutterfirebase-f5460.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-f5460-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-f5460.appspot.com',
    measurementId: 'G-HX3KPD02M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyxDL-n-o3RAA1gPC6uUUfbuVe25Pt2g',
    appId: '1:550001479730:android:d87254f5251c0711872c2b',
    messagingSenderId: '550001479730',
    projectId: 'prakflutterfirebase-f5460',
    databaseURL: 'https://prakflutterfirebase-f5460-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-f5460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOvyHUjo3uNWrrXyp4PlosmLqF5SZsEK4',
    appId: '1:550001479730:ios:bdbdd8746c49a20b872c2b',
    messagingSenderId: '550001479730',
    projectId: 'prakflutterfirebase-f5460',
    databaseURL: 'https://prakflutterfirebase-f5460-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-f5460.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOvyHUjo3uNWrrXyp4PlosmLqF5SZsEK4',
    appId: '1:550001479730:ios:bdbdd8746c49a20b872c2b',
    messagingSenderId: '550001479730',
    projectId: 'prakflutterfirebase-f5460',
    databaseURL: 'https://prakflutterfirebase-f5460-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-f5460.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU0FD6rG451mXMLk5mgNYa8e-rRTS2o7o',
    appId: '1:550001479730:web:df8293caac663028872c2b',
    messagingSenderId: '550001479730',
    projectId: 'prakflutterfirebase-f5460',
    authDomain: 'prakflutterfirebase-f5460.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-f5460-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-f5460.appspot.com',
    measurementId: 'G-BVY86NGQW7',
  );
}
